keys:
  - &kirov age1arp20x5v3fjcvn8vy9udgg5fsn5ht0fjq4qg0yt8ulh3qgs89e3strvap8
  - &articuno age1y4fmywng3a4ksqaatez7k6fyaezxlz5qclhzqdrqt0rr73dc3a4s8vntge
  - &mew age12evvsyf2kt9x7j5wtn672jwztrp8k2mmhjwdrkggazgxxfzhtc4q294je2
  - &moltres age14eql5hfcrs2dkvfulckq6ntjyvhd6ytk2mpx2qlak8lvmv2zd48qgkcvve
  - &slowpoke age1y62zzjnt22sm4lvt4dlxwvezed4r0pp5unjxegtyl73qvwdtwdaqg88m6q
creation_rules:
  - path_regex: articuno/.*\.sops\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *kirov
      - *articuno
  - path_regex: mew/.*\.sops\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *kirov
      - *mew
  - path_regex: moltres/.*\.sops\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *kirov
      - *moltres
  - path_regex: slowpoke/.*\.sops\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *kirov
      - *slowpoke
  - path_regex: \.sops\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *kirov
      - *articuno
      - *mew
      - *moltres
      - *slowpoke
