{
  imports = [
    ./atuin.nix
    ./bat.nix
    ./bitwarden.nix
    ./brave.nix
    ./btop.nix
    ./chezmoi.nix
    ./direnv.nix
    ./discord.nix
    ./eza.nix
    ./fd.nix
    ./fzf.nix
    ./git.nix
    ./jq.nix
    ./keybase.nix
    ./neovim.nix
    ./niri
    ./nix.nix
    ./nx.nix
    ./pay-respects.nix
    ./ripgrep.nix
    ./starship.nix
    ./tmux.nix
    ./wezterm.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
