{
  imports = [
    ./atuin.nix
    ./bat.nix
    ./bitwarden.nix
    ./brave.nix
    ./btop
    ./chezmoi.nix
    ./direnv.nix
    ./discord.nix
    ./dms
    ./eza.nix
    ./fd.nix
    ./flatpak.nix
    ./fzf.nix
    ./git.nix
    ./jq.nix
    ./keybase.nix
    ./matugen.nix
    ./mpv.nix
    ./neovim.nix
    ./niri
    ./nix.nix
    ./nx.nix
    ./parallel.nix
    ./pay-respects.nix
    ./podman.nix
    ./ripgrep.nix
    ./starship
    ./trash-cli.nix
    ./tmux.nix
    ./vicinae
    ./wezterm
    ./yazi.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
