{
  imports = [
    ./atuin.nix
    ./bat.nix
    ./bitwarden.nix
    ./bottom.nix
    ./brave.nix
    ./btop
    ./direnv.nix
    ./discord.nix
    ./dms
    ./eza.nix
    ./fd.nix
    ./fish.nix
    ./flatpak.nix
    ./fzf.nix
    ./git.nix
    ./jq.nix
    ./jujutsu.nix
    ./keybase.nix
    ./matugen.nix
    ./mpv.nix
    ./neovim.nix
    ./niri
    ./nix.nix
    ./nx.nix
    ./parallel.nix
    ./pay-respects.nix
    ./podman.nix
    ./ripgrep.nix
    ./ssh.nix
    ./starship.nix
    ./steam.nix
    ./syncthing.nix
    ./trash-cli.nix
    ./tmux.nix
    ./vicinae
    ./wezterm.nix
    ./yazi.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
