{
  imports = [
    ./beszel-agent
    ./boot.nix
    ./btrfs
    ./dbus.nix
    ./fish.nix
    ./flatpak.nix
    ./fwupd.nix
    ./gui.nix
    ./impermanence.nix
    ./lanzaboote.nix
    ./networking
    ./nix
    ./pam.nix
    ./podman.nix
    ./sops.nix
    ./ssh.nix
    ./steam.nix
    ./sudo.nix
    ./system-packages.nix
    ./time.nix
    ./tpm2.nix
    ./user.nix
    ./zswap.nix
  ];
}
