{
  imports = [
    ./boot.nix
    ./btrfs.nix
    ./flatpak.nix
    ./gui.nix
    ./impermanence.nix
    ./networking.nix
    ./nix.nix
    ./pam.nix
    ./podman.nix
    ./secure-boot.nix
    ./ssh.nix
    ./system-packages.nix
    ./time.nix
    ./tpm2.nix
    ./user.nix
    ./zswap.nix
  ];
}
