general:
  log_level: INFO
  # test_run: true
  timer: 10

job_defaults:
  max_strikes: 3
  min_days_between_searches: 7
  max_concurrent_searches: 3

jobs:
  remove_bad_files:
  remove_done_seeding:
  remove_failed_downloads:
  remove_failed_imports:
    message_patterns:
      - "Not a Custom Format upgrade for existing*"
      - "Not an upgrade for existing*"
      - "*Found potentially dangerous file with extension*"
      - "Invalid video file*"
      - "No files found are eligible for import*"
      - "One or more episodes expected in this release were not imported or missing from the release"
  remove_metadata_missing:
  remove_missing_files:
  remove_orphans:
  remove_slow:
  remove_stalled:
  remove_unmonitored:
  search_unmet_cutoff:
  search_missing:

instances:
  sonarr:
    - base_url: "http://sonarr:8989"
      api_key: !ENV SONARR_API_KEY
  radarr:
    - base_url: "http://radarr:7878"
      api_key: !ENV RADARR_API_KEY

download_clients:
  qbittorrent:
    - base_url: "http://gluetun:8080"
      username: !ENV QBIT_USERNAME
      password: !ENV QBIT_PASSWORD
