name: "CI: flake check"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
      # https://github.com/DeterminateSystems/magic-nix-cache/issues/154
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix flake check`
        run: nix flake check --all-systems --build-all
