name: "Nix CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v7
      - uses: wimpysworld/nothing-but-nix@v10
      - uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci
          version: latest
      - uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-auth-sock: /tmp/nix_ssh_agent.sock
      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          extra-conf: |
            extra-substituters = https://cache.kanto.casa
            extra-trusted-public-keys = cache.kanto.casa:GM3kG8olIePwNnq3/0DnyPFRPMtQ/DJbyMcO6QuIbOs=
            post-build-hook = ${{ github.workspace }}/.github/scripts/nix-cache-upload.sh
      - uses: DeterminateSystems/flake-checker-action@v13
      - name: Run `nix flake check`
        run: nix flake check --build-all
