btrbk_ssh_key: ENC[AES256_GCM,data:rSIQmloHK8FLuV7JAtsDkUjGF4H3p2y9ZOISYSMfRIqwFJkoVCMz9eWiVolzNQCViaGpkm87HI35/im21K0Xl92yOo+93+iyNw4v1HUyT64j56tSU3bINZqILFboE4zTjj1WtBhrQWtUuZ8VItPeXdkHcm8ycU/6wj9sOYuwDZGgOEVtGxoX3jKZoKO0dmfVrk/Vwe/yxAoQEyeo0ZfnjI3dGfDslYx62OLFKpkVVrQ0mkEtAkpyCb/UfOEEbU+PrdG+llHDy4+oI7KynDxkHEyEaB0FSfzwQ86tYhBEOesvSEBsCMIdE8V+OwOOOznHPecIAyH6IMS9EBIDULDZ4swHi4Zigehm5seGoLgetczEQ+rJU0OyPhr3FKdE/sqDKLABUOApP+TENJzsVroVQFPGIFZ5fytTuQRfQkUnsaJuWLcdbtA6nc+ffCllvmjpOI1xQVVI4c/uEhj9R9kedNoNu63x/IXtElodZI48ig/zlD6uQncLfPdgOG3GeM6Fmwru,iv:Ngtj1C/MjfV9jwU1njDgl5kqXQXx6yRPjQdpmMf135c=,tag:z8KQYyWPsGchjNagpD+2mw==,type:str]
sops:
    age:
        - recipient: age1arp20x5v3fjcvn8vy9udgg5fsn5ht0fjq4qg0yt8ulh3qgs89e3strvap8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbHB1VmNkSDlNOGhPZisr
            U3g5Yk9iakVXT29YVWtIQktxeWtMR1h5MVhrCklLb3ZIdnA4c3YwVDBjanJrdVc4
            SVBvSVdwNFBkN0pPVno3N3JFcjVNeFkKLS0tIG1vTXp4T2c4TEdRRWxlaWJURVBj
            eDhLdTFXcktYRWROMTVYZWhVUm5nczAKcY6e0AjHcR4Dy7uZj6jYMLBCzQ62Odi1
            BSF81k7XSw//2JQwSGTvVP3jIKWfrOrnnJT1nVmZH5QN1fN+ChJnrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12evvsyf2kt9x7j5wtn672jwztrp8k2mmhjwdrkggazgxxfzhtc4q294je2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRFJudFJtYXFLcE5tMGZ1
            SVRCVHpVV0FWazZwazNyckprLy9xUWVpTUdvCnBCNDNucFg2TXRuTHNyMW9RRnNV
            dlo2K01IeTJ2Wk0yMkhCV0pta0hYV0UKLS0tIHZLekZITXZXR1BvQU5ndHJ4K2Q1
            blRPbE5jMWE1SGQ1Uzd3S0g0NjFDT0kKFV2SBGeONx/SYLut4asti3KcTTbRrlEd
            7Cb8N5bVFfPX8O5FQBhkN5aDp+kZp10oATbz+CiMtfNl2Iuzk1weZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14eql5hfcrs2dkvfulckq6ntjyvhd6ytk2mpx2qlak8lvmv2zd48qgkcvve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRDZIT2VNRkFxZUtFOTRC
            eGV2SlZpellPU0RLRDExNHNMbkQvUWMwMjBJClZCcnhaTzRPSWcwRndxMjFUQlc2
            SnpIV2Q0Yy9Nd2kya0Z4bEkxbFZTTU0KLS0tIGhoQTF1UFFZSjUwYklmTEJJemQy
            MVRQREZZUHB5YzhYajBXWXZMaHVCZ0UKB+V7OEKOGq0RIOjxB76I0FnUMgC7pEb4
            OnzOJiIv/9BEin/ji6j721JTUz3rwUjF7swGLJzD+leFCNOc16C8jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T08:21:42Z"
    mac: ENC[AES256_GCM,data:5APmG+gS/KAgn0Bswg87l9czob+z+tZ16jRODx3Rim06076wo7OMWqMxjACCMzU8H7UNfLdPTAYIajCeLfdg9HCs6U1JzQMP74tu8QSiyBj+V7HPgQDxZe+lIhcaxzFJegTy3BxSKg+ZsIU46ZyHay/7CHgu/HvdNFRzKEavY6E=,iv:MrdCK7xmj704XKOrclXRYsfu2jIZ0REHb1HunwjKCa0=,tag:IiZNHZ60ldC+yk5JVwQnIg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
